---
name: "hello to main developer"
on:
  push:
    branches:
      - developer
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Hello to main developer"
        run: echo "Hello to main developer"
